In [15]:
import numpy as np
from skimage.io import imread
from skimage import img_as_float
from skimage.color import rgb2gray
from keras.models import load_model
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

xhat = np.zeros(shape=(10, 77, 196))

for i in range(10):
    num = i + 1
    #xhat[i] = rgb2gray(img_as_float(imread('D:\\졸프\\sound\\test\\test_' + str(num) + '.png')))
    temp = rgb2gray(img_as_float(imread('D:\\졸프\\sound\\test\\test_' + str(num) + '.png')))
    xhat[i] = np.resize(temp, (77, 196))

xhat = xhat.reshape(xhat.shape[0], 77, 196, 1).astype('float32')
print(xhat.shape)

model = load_model('D:\\졸프\\CNN_mel\\[Before]cnn_scream_model.h5')
y_pred = model.predict(xhat, batch_size=20, verbose=2) # 확률값임
print(y_pred)
y_pred = np.argmax(y_pred, axis=1).reshape(-1, 1) # 정수 형태의 레이블로 변환


for j in range(10):
    print('Predict: ', str(y_pred[j]))
    
y_test = np.zeros(10)
print(y_test)
# y_test = np.argmax(y_test, axis=1).reshape(-1, 1)
# confusion matrix 결과 출력
print("----------------- Confusion Matrix -----------------\n")
print(confusion_matrix(y_test, y_pred))

# classification_report 결과 출력
print("\n\n--------------- Classification Report ---------------\n")
print(classification_report(y_test, y_pred))

(10, 77, 196, 1)
[[9.9633610e-01 3.6638984e-03]
 [9.8932260e-01 1.0677359e-02]
 [9.4787944e-03 9.9052119e-01]
 [1.0772815e-01 8.9227182e-01]
 [9.9984789e-01 1.5204954e-04]
 [1.2151769e-01 8.7848228e-01]
 [2.6536109e-02 9.7346389e-01]
 [8.8754165e-01 1.1245836e-01]
 [9.9042577e-01 9.5743006e-03]
 [9.0376925e-01 9.6230790e-02]]
Predict:  [0]
Predict:  [0]
Predict:  [1]
Predict:  [1]
Predict:  [0]
Predict:  [1]
Predict:  [1]
Predict:  [0]
Predict:  [0]
Predict:  [0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
----------------- Confusion Matrix -----------------

[[6 4]
 [0 0]]


--------------- Classification Report ---------------

              precision    recall  f1-score   support

         0.0       1.00      0.60      0.75        10
         1.0       0.00      0.00      0.00         0

    accuracy                           0.60        10
   macro avg       0.50      0.30      0.37        10
weighted avg       1.00      0.60      0.75        10



C:\Users\cyber\AppData\Roaming\Python\Python37\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
